# Setup and configure ruby things for reddit app


# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no

  tasks:
#  - name: Install mongodb package
  - name: get apt key
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927
  - name: Add MongoDB repository into sources list
    apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
        state: present
  - name: Install MongoDB package
    apt:
        name: mongodb-org
        allow_unauthenticated: yes
        update_cache: yes
  become: yes
#    debug:
#      msg: "В этом сценарии нужно добавить модули для установки mongodb, после можно удалить вызов модуля debug, который выводит это сообщение"

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no

  tasks:
  - name: Remove me after adding real things
    debug:
      msg: "В этом сценарии нужно добавить модули для деплоя приложения, после можно удалить вызов модуля debug, который выводит это сообщение"